services:
  postgres:
    image: postgres:17-alpine
    container_name: eshop-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - eshop-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: eshop-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@eshop.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - eshop-network

volumes:
  postgres_data:
    driver: local
    name: eshop_postgres_data
  pgadmin_data:
    driver: local
    name: eshop_pgadmin_data

networks:
  eshop-network:
    driver: bridge